name: Deploy Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir .public && mv * .public && mv .public public
      - uses: actions/upload-pages-artifact@v4
        id: deployment
        with:
          path: public/

      - uses: actions/deploy-pages@v4
